project:
  type: website
  output-dir: docs

website:
  title: "CStein2000.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Data Viz
        menu: 
        - href: tidyanalysis1.qmd
          text: Amazon Annual Reports
        - href: tidyanalysis2.qmd
          text: Coffee Ratings

format:
  html:
    theme:
        light: sandstone
        dark: vapor
    css: styles.css
    toc: true
    page-layout: full


